# This is a basic workflow to help you get started with Actions

name: Scrape

# Controls when the workflow will run
on:
  schedule:
    -  cron: '50 * * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  scrape:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-r@master

      - name: Install packages
        run: |
          R -e 'install.packages("rvest")'
      
      - name: Scrape
        run: Rscript scrape.R
        
